apiVersion: v1
kind: Service
metadata:
  name: mongo
  namespace: msslabs
  labels:
    app: mongo
spec:
  type: NodePort
  ports:
    - port: 27017
      nodePort: 27017
      protocol: TCP
  selector:
    app: mongo
