apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: msslabs
  labels:
    app: frontend
spec:
  type: LoadBalancer
  ports:
    - nodePort: 31353
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: frontend
